// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Models;

#nullable disable

namespace MyShop.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyShop.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Skoda",
                            Color = "Black",
                            ImageFileName = "1.jpg",
                            Model = "Octavia",
                            Price = 45000.00m,
                            Type = "Sedan",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes",
                            Color = "White",
                            ImageFileName = "2.jpg",
                            Model = "GLE",
                            Price = 3500000.00m,
                            Type = "SUV",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "VW",
                            Color = "Blue",
                            ImageFileName = "3.jpg",
                            Model = "Passat",
                            Price = 1100.00m,
                            Type = "Combi",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Ford",
                            Color = "White",
                            ImageFileName = "4.jpg",
                            Model = "Transit",
                            Price = 200000.00m,
                            Type = "Bus",
                            Year = 2023
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
